name = "examples"
description = "Rtmidi examples"
version = "0.1.0-dev"

authors = ["Shuihuzhuan"]
maintainers = ["Shuihuzhuan <shuihuzhuan@free.fr>"]
maintainers-logins = ["shuihuzhuan"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = "https://github.com/HROMANO/Rtmidiada"
tags = ["multimedia", "midi"]

executables = ["examples"]

[[depends-on]]
rtmidi = "*"

[[pins]]
rtmidi = { path = ".." }
